version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Tweak PATH
          command: echo 'PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install Rust
          command: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$(cat rust-toolchain) -y
      - run:
          name: Add WASM32 support
          command: rustup target add wasm32-unknown-unknown --toolchain $(cat rust-toolchain)
      - run:
          name: Install yarn
          command: sudo npm install -g yarn && sudo chmod +x /usr/local/bin/yarn
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "yarn.lock" }}
            - node-modules-cache-
      - run:
          name: Install node dependencies
          command: yarn
      - save_cache:
          key: node-modules-cache-{{ checksum "yarn.lock" }}-{{ epoch }}
          paths:
            - ./node_modules
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-{{ arch }}
      - run:
          name: Install wasm-bindgen-cli
          command: CARGO_TARGET_DIR=target cargo install --git https://github.com/alexcrichton/wasm-bindgen.git --rev $(cargo read-manifest --locked | jq '.dependencies[]|select(.name == "wasm-bindgen")|.source' -r | cut -d= -f2) -f
      - run:
          name: Install wasm-gc
          command: CARGO_TARGET_DIR=target cargo install wasm-gc -f
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ epoch }}
          paths:
            - ~/.cargo
            - ./target
