#!/bin/sh -eu
main=src/wasm/semantic_editor.js
bg=src/wasm/semantic_editor_bg.js

wasm2es6js src/wasm/semantic_editor_bg.wasm -o "$bg" --base64
awk 'BEGIN {print "/*ignore jslint start*/"} NR==3 {print "const WebAssembly = window.WebAssembly;"} END {print "/*ignore jslint end*/"} {print}' "$bg" > "$bg.new"
mv "$bg.new" "$bg"
awk 'BEGIN {print "/*ignore jslint start*/"} END {print "/*ignore jslint end*/"} {print}' "$main" > "$main.new"
mv "$main.new" "$main"
