#!/bin/sh -eu
bg=src/wasm/semantic_editor_bg.js

RUST_BACKTRACE=1 wasm2es6js src/wasm/semantic_editor_bg.wasm -o "$bg" --base64

awk '
  BEGIN {print "/*ignore jslint start*/"}
  NR==3 {print "const WebAssembly = window.WebAssembly;"}
  END {print "/*ignore jslint end*/"}
  {print}
' "$bg" > "$bg.new"
mv "$bg.new" "$bg"
